# Intel RealSense D435i Camera Configuration - Agricultural Enhanced
camera:
  # High-quality resolution for agricultural use
  color_width: 848
  color_height: 480
  depth_width: 848  
  depth_height: 480
  fps: 30
  
  # Agricultural environment optimization
  enable_depth: true
  enable_color: true
  enable_imu: false
  
  # Enhanced depth processing for outdoor use
  depth_filters:
    decimation: true
    spatial: true
    temporal: true
    hole_filling: true
    threshold: true
  
  # Outdoor lighting optimization  
  auto_exposure: true
  exposure: 8500        # Optimized for outdoor use
  gain: 64             # Moderate gain for good SNR
  laser_power: 240     # High laser power for outdoor depth
  
  # Agricultural specific settings
  agricultural_mode: true
  dust_compensation: true
  vibration_filtering: true
  
# Enhanced GUI Settings
gui:
  window_title: "Agricultural SLAM System v2.0 - Enhanced"
  window_width: 1600
  window_height: 1000
  camera_display_width: 848
  camera_display_height: 480
  
  # Performance settings
  target_fps: 30
  enable_3d_visualization: true
  enable_performance_monitoring: true