# Enhanced SLAM Configuration for Agricultural Equipment Tracking
slam:
  # Enhanced feature detection
  max_features: 2000
  min_features_for_tracking: 50
  min_features_for_keyframe: 75
  
  # Robust visual odometry for agricultural environments
  min_matches: 12
  ransac_threshold: 2.0
  ransac_iterations: 1000
  max_translation_per_frame: 3.0
  max_rotation_per_frame: 1.0
  
  # Agricultural movement filtering (enhanced)
  min_translation_threshold: 0.05      # 5cm minimum movement
  min_rotation_threshold: 0.087        # 5 degrees
  stationary_threshold: 0.05           # 5cm stationary detection
  movement_consistency_threshold: 0.03 
  
  # Keyframe creation (agricultural optimized)
  keyframe_distance_threshold: 0.3     # 30cm
  keyframe_angle_threshold: 0.174      # 10 degrees
  
  # Agricultural-specific features
  agricultural_mode: true
  crop_row_detection: true
  ground_plane_estimation: true
  field_boundary_tracking: true
  robust_tracking: true
  loop_closure_enabled: true
  filter_small_movements: true
  stationary_detection_enabled: true
  
  # Performance optimization
  adaptive_thresholding: true
  performance_monitoring: true
  gpu_acceleration: false  # Set to true if OpenGL available
  
# Enhanced Camera calibration (D435i agricultural optimized)  
camera_calibration:
  fx: 615.0
  fy: 615.0
  cx: 424.0    # Adjusted for 848x480 resolution
  cy: 240.0
  
  # Enhanced distortion model
  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0
  
  # Agricultural calibration validation
  agricultural_validated: false
  reprojection_error_threshold: 1.0
  outdoor_suitability_threshold: 0.7

# Enhanced trajectory settings
trajectory:
  save_format: "npz"
  auto_save: true
  save_interval_seconds: 300  # Auto-save every 5 minutes
  max_points: 20000
  precision_tracking: true
  distance_validation: true
  
# Performance monitoring
performance:
  enable_monitoring: true
  target_fps: 30
  alert_on_low_fps: true
  alert_on_high_cpu: true
  export_reports: true